apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: backend
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 80
