apiVersion: v1
kind: Pod
metadata:
  name: frontend-client
  namespace: frontend
  labels:
    app: frontend-client
    app.kubernetes.io/name: frontend-client
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  containers:
  - name: client
    image: curlimages/curl:8.8.0
    command:
    - sh
    - -c
    - sleep 3600
