apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-compute
  namespace: quota-lab
  labels:
    app.kubernetes.io/name: quota-compute
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
