apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-objects
  namespace: quota-lab
  labels:
    app.kubernetes.io/name: quota-objects
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  hard:
    pods: "5"
    services: "3"
    configmaps: "5"
    secrets: "5"
