apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-min-max
  namespace: limitrange-lab
  labels:
    app.kubernetes.io/name: limitrange-min-max
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  limits:
  - type: Container
    min:
      cpu: "50m"
      memory: "64Mi"
    max:
      cpu: "1"
      memory: "512Mi"
