apiVersion: v1
kind: Pod
metadata:
  name: pod-above-limit
  namespace: limitrange-lab
  labels:
    app: pod-above-limit
    app.kubernetes.io/name: pod-above-limit
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    resources:
      requests:
        cpu: "1200m"
        memory: "600Mi"
      limits:
        cpu: "1200m"
        memory: "600Mi"
