apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: resources-lab
  labels:
    app: stress-test
    app.kubernetes.io/name: stress-test
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  restartPolicy: Never
  containers:
  - name: stress
    image: polinux/stress
    command:
    - stress
    args:
    - "--cpu"
    - "1"
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "64M"
    - "--timeout"
    - "90s"
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
