apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dev
  namespace: dev
  labels:
    app: web-dev
    app.kubernetes.io/name: web-dev
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-dev
  template:
    metadata:
      labels:
        app: web-dev
        app.kubernetes.io/name: web-dev
        app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
