apiVersion: v1
kind: Service
metadata:
  name: web-dev
  namespace: dev
  labels:
    app.kubernetes.io/name: web-dev
    app.kubernetes.io/part-of: kubernetes-lab-namespaces-resources
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: web-dev
  ports:
  - port: 80
    targetPort: 80
