name: Validate Kubernetes YAML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-manifests:
    name: Validate manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Validate YAML syntax (manifests)
        run: |
          yamllint -d "{extends: default, rules: {line-length: disable, document-start: disable}}" manifests/

      - name: Install kubeconform
        run: |
          KUBECONFORM_VERSION="v0.6.7"
          curl -sSL "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" -o kubeconform.tar.gz
          tar -xzf kubeconform.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/kubeconform
          kubeconform -v

      - name: Validate Kubernetes manifests (sem cluster)
        run: |
          kubeconform -strict -summary -recursive -ignore-missing-schemas manifests/
